install: |
  sudo apt-get update
  sudo gem install pdd
release:
  script: |-
    pdd -f /dev/null
    sudo bundle install
    rake
    find . -name '*.xsd' -exec sed -i "s/SNAPSHOT/${tag}/g" \{} \;
    find . -name '*.xsd' -exec git add \{} \;
    git commit -m "version set to ${tag}"
    cp -r xsd /tmp
    git checkout gh-pages
    mkdir "${tag}"
    cp -r /tmp/xsd "${tag}"
    git add "${tag}"
    git commit -m "XSD ${tag}"
  commanders:
  - yegor256
architect:
- yegor256
- davvd
merge:
  commanders: []
deploy: {}
