install: |
  sudo apt-get update
  sudo gem install pdd
  sudo apt-get install -y pandoc
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit -1
    pdd -f /dev/null
    bundle install
    rake default[${tag}]
    rake site[${tag}] validate_site[${tag}]
    cp -r target/site /tmp
    git checkout gh-pages
    for d in $(ls /tmp/site); do rm -rf $d; cp -r /tmp/site/$d .; git add $d; done
    git commit --allow-empty -m "${tag}"
  commanders:
    - yegor256
architect:
- yegor256
- davvd
merge:
  commanders:
    - yegor256
  script: |-
    pdd -f /dev/null
    bundle install
    rake
deploy:
  script: |-
    echo 'There is no such thing as deploy'
    exit -1
