install: |
  sudo apt-get update
  sudo gem install pdd
release:
  script: |-
    pdd -f /dev/null
    bundle install
    rake
    find . -name '*.xsd' -exec sed -i "s/SNAPSHOT/${tag}/g" \{} \;
    find . -name '*.xsd' -exec git add \{} \;
    git commit -m "version set to ${tag}"
    cp -r xsd /tmp
    git checkout gh-pages
    mkdir "${tag}"
    cp -r /tmp/xsd "${tag}"
    git add "${tag}"
    rm -rf latest
    mkdir latest
    cp -r /tmp/xsd latest
    git add latest
    git commit -m "XSD ${tag}"
  commanders:
    - yegor256
architect:
- yegor256
- davvd
merge:
  commanders:
    - yegor256
  script: |-
    pdd -f /dev/null
    bundle install
    rake
deploy:
  script: |-
    echo 'There is no such thing as deploy'
    exit -1
