language: ruby
rvm:
  - 2.6.0
cache: bundler
branches:
  only:
    - master
install:
  - travis_retry bundle update
  - mvn dependency:get -DgroupId=net.sf.saxon -DartifactId=Saxon-HE -Dversion=9.8.0-8
script:
  - rake

